// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @react-native-community/netinfo
#include <winrt/ReactNativeNetInfo.h>

// Includes from react-native-custom-window
#include <winrt/ReactNativeCustomWindow.h>

// Includes from react-native-fs
#include <winrt/RNFS.h>

// Includes from react-native-screens
#include <winrt/RNScreens.h>

// Includes from react-native-sensitive-info
#include <winrt/RNSensitiveInfoCPP.h>

// Includes from react-native-svg
#include <winrt/RNSVG.h>

// Includes from react-native-video
#include <winrt/ReactNativeVideoCPP.h>

// Includes from react-native-xaml
#include <winrt/ReactNativeXaml.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @react-native-community/netinfo
    packageProviders.Append(winrt::ReactNativeNetInfo::ReactPackageProvider());
    // IReactPackageProviders from react-native-custom-window
    packageProviders.Append(winrt::ReactNativeCustomWindow::ReactPackageProvider());
    // IReactPackageProviders from react-native-fs
    packageProviders.Append(winrt::RNFS::ReactPackageProvider());
    // IReactPackageProviders from react-native-screens
    packageProviders.Append(winrt::RNScreens::ReactPackageProvider());
    // IReactPackageProviders from react-native-sensitive-info
    packageProviders.Append(winrt::RNSensitiveInfoCPP::ReactPackageProvider());
    // IReactPackageProviders from react-native-svg
    packageProviders.Append(winrt::RNSVG::ReactPackageProvider());
    // IReactPackageProviders from react-native-video
    packageProviders.Append(winrt::ReactNativeVideoCPP::ReactPackageProvider());
    // IReactPackageProviders from react-native-xaml
    packageProviders.Append(winrt::ReactNativeXaml::ReactPackageProvider());
}

}
